//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Schedure.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account_BenhNhan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Account_BenhNhan()
        {
            this.Registers = new HashSet<Register>();
        }
    
        public int IDAccountBN { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Avatar { get; set; }
        public string FullName { get; set; }
        public Nullable<bool> Male { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string Adress { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string TieuSu { get; set; }
        public string Status { get; set; }
        public Nullable<int> BenhNhan_Id { get; set; }
    
        public virtual DM_BenhNhan DM_BenhNhan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Register> Registers { get; set; }
    }
}
