//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Schedure.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChuyenKhoa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ChuyenKhoa()
        {
            this.PhongKhams = new HashSet<PhongKham>();
        }
    
        public int IDChuyenKhoa { get; set; }
        public string Avatar { get; set; }
        public string Name { get; set; }
        public Nullable<int> TimeUse { get; set; }
        public string Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhongKham> PhongKhams { get; set; }
    }
}
