//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Schedure.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_BenhNhan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DM_BenhNhan()
        {
            this.Account_BenhNhan = new HashSet<Account_BenhNhan>();
        }
    
        public int BenhNhan_Id { get; set; }
        public string TenBenhNhan { get; set; }
        public string Ho { get; set; }
        public string MaYTe { get; set; }
        public string GioiTinh { get; set; }
        public string SoTheBHYT { get; set; }
        public string SoVaoVien { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public short NamSinh { get; set; }
        public string CMND { get; set; }
        public string TenKhongDau { get; set; }
        public string GhiChu { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public Nullable<int> NguoiTao_Id { get; set; }
        public string DiaChiThuongTru { get; set; }
        public string DiaChiLienLac { get; set; }
        public string SoDienThoai { get; set; }
        public string DiaChiCoQuan { get; set; }
        public string Ten { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Account_BenhNhan> Account_BenhNhan { get; set; }
    }
}
