//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Schedure.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doctor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Doctor()
        {
            this.HistoryKhamBenhs = new HashSet<HistoryKhamBenh>();
            this.Registers = new HashSet<Register>();
        }
    
        public int IDDoctor { get; set; }
        public Nullable<int> IDSpecia { get; set; }
        public string FullName { get; set; }
        public string Avatar { get; set; }
        public string Sumary { get; set; }
        public string TrainingProcess { get; set; }
        public string Study { get; set; }
        public string Status { get; set; }
    
        public virtual Specia Specia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HistoryKhamBenh> HistoryKhamBenhs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Register> Registers { get; set; }
    }
}
