//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Schedure.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LichLamViec
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LichLamViec()
        {
            this.Registers = new HashSet<Register>();
        }
    
        public int IDLich { get; set; }
        public Nullable<int> IDDoctor { get; set; }
        public Nullable<System.TimeSpan> Time { get; set; }
        public Nullable<int> IDTimeSlot { get; set; }
        public Nullable<int> Creater_Id { get; set; }
        public Nullable<System.DateTime> CreaterDate { get; set; }
    
        public virtual Account_NhanVien Account_NhanVien { get; set; }
        public virtual Doctor Doctor { get; set; }
        public virtual TimeSlot TimeSlot { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Register> Registers { get; set; }
    }
}
