//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Schedure.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Register
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Register()
        {
            this.HistoryKhamBenhs = new HashSet<HistoryKhamBenh>();
        }
    
        public int IDRegister { get; set; }
        public Nullable<int> IDAccount { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string Message { get; set; }
        public string Status { get; set; }
        public int IDLich { get; set; }
        public string Phone { get; set; }
        public Nullable<System.DateTime> NgayKham { get; set; }
    
        public virtual Account_BenhNhan Account_BenhNhan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HistoryKhamBenh> HistoryKhamBenhs { get; set; }
        public virtual LichLamViec LichLamViec { get; set; }
    }
}
