//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Schedure.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ToaThuoc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ToaThuoc()
        {
            this.CTToaThuocs = new HashSet<CTToaThuoc>();
        }
    
        public int IDToaThuoc { get; set; }
        public Nullable<int> IDHistory { get; set; }
        public string CachDung { get; set; }
        public string GhiChu { get; set; }
        public Nullable<int> Gia { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTToaThuoc> CTToaThuocs { get; set; }
        public virtual HistoryKhamBenh HistoryKhamBenh { get; set; }
    }
}
