//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchedureDTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account_BenhNhanDTO
    {
        public Account_BenhNhanDTO()
        {
            this.Registers = new HashSet<RegisterDTO>();
        }
    
        public int IDAccountBN { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public string Status { get; set; }
        public Nullable<int> BenhNhan_Id { get; set; }
        public string Token { get; set; }
        public Nullable<System.DateTime> TokenExpiration { get; set; }

        public virtual string MaYTe { get; set; }
    
        public virtual ICollection<RegisterDTO> Registers { get; set; }
    }
}
