//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchedureDTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account_NhanVienDTO
    {
        public int IDAccountNV { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public Nullable<int> NhanVien_Id { get; set; }
        public string Status { get; set; }
        public Nullable<int> IDPosition { get; set; }

        public virtual string TenNhanVien { get; set; }
        public virtual string MaNhanvien { get; set; }

        public virtual PositionDTO Position { get; set; }
    }
}
