//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchedureDTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTToaThuocDTO
    {
        public int IDCT { get; set; }
        public int IDToaThuoc { get; set; }
        public Nullable<int> IDThuoc { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<int> GiaTien { get; set; }
        public string Thuoc_Name { get; set; }
        public string Thuoc_DonVi { get; set; }
    }
}
