//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchedureDTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistoryKhamBenhDTO
    {
        public int IDHistory { get; set; }
        public Nullable<int> IDRegister { get; set; }
        public Nullable<int> IDDoctor { get; set; }
        public Nullable<int> ICD { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<int> Mach { get; set; }
        public Nullable<int> NhipTho { get; set; }
        public Nullable<int> ChieuCao { get; set; }
        public Nullable<int> NhieuDo { get; set; }
        public Nullable<int> HuyetApTT { get; set; }
        public Nullable<int> HuyetApTD { get; set; }
        public Nullable<int> CanNang { get; set; }
        public string TrieuChungLS { get; set; }
        public string ChuanDoanSoBo { get; set; }
        public string CachGiaiQuyet { get; set; }
    }
}
