//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchedureDTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class LichLamViecDTO
    {
        public int IDLich { get; set; }
        public Nullable<int> IDDoctor { get; set; }
        public Nullable<System.TimeSpan> Time { get; set; }
        public Nullable<int> IDTimeSlot { get; set; }
        public Nullable<int> Creater_Id { get; set; }
        public Nullable<System.DateTime> CreaterDate { get; set; }

        public TimeSlotDTO TimeSlot { get; set; }
        public DoctorDTO Doctor { get; set; }
    }
}
