//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchedureDTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class LichLamViecDTO
    {
        public LichLamViecDTO()
        {
            this.Registers = new HashSet<RegisterDTO>();
        }

        public int IDLich { get; set; }
        public Nullable<int> NhanVien_Id { get; set; }
        public Nullable<int> IDTimeSlot { get; set; }
        public Nullable<int> Creater_Id { get; set; }
        public Nullable<System.DateTime> CreaterDate { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Status { get; set; }
        public Nullable<int> IDPhongKham { get; set; }
        public Nullable<int> Modified_Id { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }

        public virtual TimeSlotDTO TimeSlot { get; set; }
        public virtual DoctorDTO Doctor { get; set; }
        public virtual PhongBanDTO PhongKham { get; set; }
        public virtual ICollection<RegisterDTO> Registers { get; set; }
    }
}
