//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchedureDTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhongBanDTO
    {
        public PhongBanDTO()
        {
            Doctors = new List<DoctorDTO>();
        }

        public int IDPhongBan { get; set; }
        public Nullable<int> IDChuyenKhoa { get; set; }
        public Nullable<int> PhongBan_Id { get; set; }
        public string Status { get; set; }
        public string TenPhongBan { get; set; }

        public virtual ChuyenKhoaDTO ChuyenKhoa { get; set; }
        public virtual List<DoctorDTO> Doctors { get; set; }
    }
}
