//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchedureDTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhongKhamDTO
    {
        public PhongKhamDTO()
        {
            Doctors = new List<DoctorDTO>();
        }

        public int IDPhongKham { get; set; }
        public string Name { get; set; }
        public Nullable<int> IDChuyenKhoa { get; set; }

        public ChuyenKhoaDTO ChuyenKhoa { get; set; }
        public List<DoctorDTO> Doctors { get; set; }
    }
}
