//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchedureDTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegisterDTO
    {
        public int IDRegister { get; set; }
        public Nullable<int> IDAccount { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string Message { get; set; }
        public string Status { get; set; }
        public int IDLich { get; set; }
        public Nullable<System.DateTime> NgayKham { get; set; }
        public string Phone { get; set; }

        public LichLamViecDTO LichLamViec { get; set; }
        public Account_BenhNhanDTO Account_BenhNhan { get; set; }
    }
}
