//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchedureDTO
{
    using System;
    using System.Collections.Generic;

    public partial class ToaThuocDTO
    {
        public int IDToaThuoc { get; set; }
        public Nullable<int> IDHistory { get; set; }
        public string CachDung { get; set; }
        public string GhiChu { get; set; }
        public Nullable<int> Gia { get; set; }
    }
}
