// Copyright 2012 Google Inc. All rights reserved.
// Container Version: 8
(function(w,g){w[g]=w[g]||{};})(window,'google_tag_manager');(function(){

var __sdl;(function(){function a(){return!!(Object.keys(h("horiz.pix")).length||Object.keys(h("horiz.pct")).length||Object.keys(h("vert.pix")).length||Object.keys(h("vert.pct")).length)}function b(a){for(var b=[],c=a.split(","),d=0;d<c.length;d++){var e=Number(c[d]);if(isNaN(e))return[];k.test(c[d])||b.push(e)}return b}function c(){var a=0,b=0;return function(){var c,d={rb:0,sb:0};d=la();c=d;var e=c.rb;a=Math.max(r.scrollLeft+
c.sb,a);b=Math.max(r.scrollTop+e,b);return{Qc:a,Rc:b}}}function d(a,b,c,d){var e=h(b),f={},g;for(g in e){f.threshold=g;if(e.hasOwnProperty(f.threshold)){var k=Number(f.threshold);a<k||(na({event:"gtm.scrollDepth","gtm.scrollThreshold":k,"gtm.scrollUnits":c.toLowerCase(),"gtm.scrollDirection":d,"gtm.triggers":e[f.threshold].join(",")}),oa("sdl",b,function(a){return function(b){delete b[a.threshold];return b}}(f),{}))}f={threshold:f.threshold}}}function e(){var a=v(),b=a.Qc,c=a.Rc,e=b/r.scrollWidth*
100,f=c/r.scrollHeight*100;d(b,"horiz.pix",l.Da,m.Lb);d(e,"horiz.pct",l.Ca,m.Lb);d(c,"vert.pix",l.Da,m.Mb);d(f,"vert.pct",l.Ca,m.Mb);pa("sdl","pending",!1)}function f(){var b=250,c=!1;p.scrollingElement&&p.documentElement&&n.addEventListener&&(b=50,c=!0);var d=0,f=!1,g=function(){f?d=ka(g,b):(d=0,e(),qa("sdl")&&!a()&&(ra(n,"scroll",h,void 0),ra(n,"resize",h,void 0),pa("sdl","init",!1)));f=!1},h=function(){c&&v();d?f=!0:(d=ka(g,b),pa("sdl","pending",!0))};return h}function g(a,c,d){if(c){var e=b(String(a));
oa("sdl",d,function(a){for(var b=0;b<e.length;b++){var d=String(e[b]);a.hasOwnProperty(d)||(a[d]=[]);a[d].push(c)}return a},{})}}function h(a){return sa("sdl",a,{})}var k=/^\s*$/,l={Ca:"PERCENT",Da:"PIXELS"},m={Mb:"vertical",Lb:"horizontal"},n,p,r,t=!1,v;(function(a){__sdl=a;__sdl.a="sdl";__sdl.b=["google"];__sdl.c=!0})(function(b){w(b["42"]);t||(n=q("self"),p=n.document,r=p.scrollingElement||p.body&&p.body.parentNode,v=c(),t=!0);if(r){var d=b["34"],h=
b[""],k=b[""],m=b["39"],z=b[""],D=b["40"];switch(b[""]){case l.Da:g(h,d,"horiz.pix");break;case l.Ca:g(k,d,"horiz.pct")}switch(m){case l.Da:g(z,d,"vert.pix");break;case l.Ca:g(D,d,"vert.pct")}qa("sdl")?ta("sdl","pending",void 0)||w(function(){return e()}):(ua("sdl"),pa("sdl","pending",
!0),w(function(){e();if(a()){var b=f();va(n,"scroll",b,void 0);va(n,"resize",b,void 0)}else pa("sdl","init",!1)}))}})})();

var __sp;(function(){(function(a){__sp=a;__sp.a="sp";__sp.b=["google"];__sp.c=!0})(function(a){var b=a["43"];ba("//www.googleadservices.com/pagead/conversion_async.js",function(){var c=q("google_trackConversion");if(R(c)){var d={};"DATA_LAYER"==a["10"]?d=a[""]:"USER_SPECIFIED"==a["10"]&&(d=P(a[""],"key","value"));c({google_conversion_id:a["8"],
google_conversion_label:a[""],google_custom_params:d,google_remarketing_only:!0,onload_callback:a["42"],google_gtm:ya(void 0)})||b()}else b()},b)})})();
var __e;(function(){(function(a){__e=a;__e.a="e";__e.b=["google"];__e.c=!0})(function(){return Ca})})();
var __f;(function(){(function(a){__f=a;__f.a="f";__f.b=["google"];__f.c=!0})(function(a){var b=S("gtm.referrer",1)||K.referrer,c;if(b){var d;if(a["7"]&&"URL"!=a["7"]){var e=T(String(b));d=U(e,a["7"],a[""],a[""],a[""])}else d=Da(T(String(b)));c=d}else c=String(b);return c})})();
var __cl;(function(){function a(a){var b=a.target;if(b){var d=Ea(b);d.event="gtm.click";na(d)}}(function(a){__cl=a;__cl.a="cl";__cl.b=["google"];__cl.c=!0})(function(b){if(!qa("cl")){var c=q("document");va(c,"click",a,!0);ua("cl");var d=ta("cl","legacyTeardown",void 0);d&&d()}w(b["42"])})})();


var __u;(function(){(function(a){__u=a;__u.a="u";__u.b=["google"];__u.c=!0})(function(a){var b;b=(b=a[""]?a[""]:S("gtm.url",1))||ca();var c=a["7"],d;if(c&&"URL"!=c){var e=T(String(b));d=U(e,c,"HOST"==c?a[""]:void 0,"PATH"==c?a[""]:void 0,"QUERY"==c?a[""]:void 0)}else d=Da(T(String(b)));return d})})();
var __v;(function(){(function(a){__v=a;__v.a="v";__v.b=["google"];__v.c=!0})(function(a){var b=S(a["25"].replace(/\\\./g,"."),a["11"]||1);return void 0!==b?b:a["13"]})})();
var __ua;(function(){var a;(function(a){__ua=a;__ua.a="ua";__ua.b=["google"];__ua.c=!0})(function(b){var c={},d={},e={},f={},g={};if(b["23"]){var h=b["23"];Ia(P(h["41"],"fieldName","value"),d);Ia(P(h[""],"index","group"),e);Ia(P(h[""],"index","dimension"),f);Ia(P(h[""],"index","metric"),g);b["23"]=null;h["41"]=void 0;h[""]=
void 0;h[""]=void 0;h[""]=void 0;var k=V(h,void 0);b=V(b,k)}Ia(P(b["41"],"fieldName","value"),d);Ia(P(b[""],"index","group"),e);Ia(P(b[""],"index","dimension"),f);Ia(P(b[""],"index","metric"),g);var l=Ja(b[""]),m="",n="";b["30"]&&"string"==typeof b[""]?""!==b[""]&&(n=b[""],
m=n+"."):(n=Ka(),m=n+".");var p={name:!0,clientId:!0,sampleRate:!0,siteSpeedSampleRate:!0,alwaysSendReferrer:!0,allowAnchor:!0,allowLinker:!0,cookieName:!0,cookieDomain:!0,cookieExpires:!0,cookiePath:!0,cookieUpdate:!0,legacyCookieDomain:!0,legacyHistoryImport:!0,storage:!0,useAmpClientId:!0,storeGac:!0},r={allowAnchor:!0,allowLinker:!0,alwaysSendReferrer:!0,anonymizeIp:!0,cookieUpdate:!0,exFatal:!0,forceSSL:!0,javaEnabled:!0,legacyHistoryImport:!0,nonInteraction:!0,useAmpClientId:!0,useBeacon:!0,
storeGac:!0},t=function(a){var b=[].slice.call(arguments,0);b[0]=m+b[0];l.apply(window,b)},v=function(a,b){return void 0===b?b:a(b)},z=function(a,b){if(b)for(var c in b)b.hasOwnProperty(c)&&t("set",a+c,b[c])},J=function(){},F=function(a,b,c){var d=0;if(a)for(var e in a)if(a.hasOwnProperty(e)&&(c&&p[e]||!c&&void 0===p[e])){var f=r[e]?Oa(a[e]):a[e];"anonymizeIp"!=e||f||(f=void 0);b[e]=f;d++}return d},E={name:n};F(d,E,!0);l("create",b["33"]||c.trackingId,E);t("set","&gtm",ya(!0));(function(a,c){void 0!==b[c]&&t("set",a,b[c])})("nonInteraction","26");z("contentGroup",
e);z("dimension",f);z("metric",g);var L={};F(d,L,!1)&&t("set",L);var B;b["17"]&&t("require","linkid","linkid.js");t("set","hitCallback",function(){var a=d&&d.hitCallback;R(a)&&a();b["42"]()});if("TRACK_EVENT"==b["31"]){
b["15"]&&(t("require","ec","ec.js"),J());var D={hitType:"event",eventCategory:String(b["21"]||c.category),eventAction:String(b["20"]||c.action),eventLabel:v(String,b["22"]||c.label),eventValue:v(Pa,b[""]||c.value)};F(B,D,!1);t("send",D);}else if("TRACK_SOCIAL"==b["31"]){}else if("TRACK_TRANSACTION"==b["31"]){}else if("TRACK_TIMING"==b["31"]){}else if("DECORATE_LINK"==b["31"]){}else if("DECORATE_FORM"==b["31"]){}else if("TRACK_DATA"==b["31"]){}else{b["15"]&&(t("require","ec","ec.js"),J());if(b["14"]||"DISPLAY_FEATURES"==
b[""]){var Q="_dc_gtm_"+String(b["33"]).replace(/[^A-Za-z0-9-]/g,"");t("require","displayfeatures",void 0,{cookieName:Q})}"DISPLAY_FEATURES_WITH_REMARKETING_LISTS"==b[""]&&(Q="_dc_gtm_"+String(b["33"]).replace(/[^A-Za-z0-9-]/g,""),t("require","adfeatures",{cookieName:Q}));B?t("send","pageview",B):t("send","pageview");}if(!a){var M=b["36"]?"u/analytics_debug.js":"analytics.js";b[""]&&!b["36"]&&(M="internal/"+M);a=!0;Sa(x("https:","http:","//www.google-analytics.com/"+M,d&&d.forceSSL),function(){var a=Qa();a&&a.loaded||
b["43"]();},b["43"])}})})();
var __gas;(function(){(function(a){__gas=a;__gas.a="gas";__gas.b=["google"];__gas.c=!0})(function(a){var b=V(a,void 0),c=b;c[Za]=null;c[$a]=null;var d=b=c;d["41"]=d["41"]||[];var e=d["9"];void 0!==e&&(d["41"].push({fieldName:"cookieDomain",value:e}),delete d["9"]);return b})})();



var __paused;(function(){(function(a){__paused=a;__paused.a="paused";__paused.b=[];__paused.c=!0})(function(a){w(a["43"])})})();




/*
 jQuery v1.9.1 (c) 2005, 2012 jQuery Foundation, Inc. jquery.org/license. */
var Gb=/\[object (Boolean|Number|String|Function|Array|Date|RegExp)\]/,Hb=function(a){if(null==a)return String(a);var b=Gb.exec(Object.prototype.toString.call(Object(a)));return b?b[1].toLowerCase():"object"},Ib=function(a,b){return Object.prototype.hasOwnProperty.call(Object(a),b)},La=function(a){if(!a||"object"!=Hb(a)||a.nodeType||a==a.window)return!1;try{if(a.constructor&&!Ib(a,"constructor")&&!Ib(a.constructor.prototype,"isPrototypeOf"))return!1}catch(c){return!1}for(var b in a);return void 0===
b||Ib(a,b)},V=function(a,b){var c=b||("array"==Hb(a)?[]:{}),d;for(d in a)if(Ib(a,d)){var e=a[d];"array"==Hb(e)?("array"!=Hb(c[d])&&(c[d]=[]),c[d]=V(e,c[d])):La(e)?(La(c[d])||(c[d]={}),c[d]=V(e,c[d])):c[d]=e}return c};var Ha={},sb=null,Jb=Math.random();Ha.f="GTM-P3932SV";var Kb=null,Ca=null,jb=!1,Lb="//www.googletagmanager.com/a?id="+Ha.f+"&cv=8",Mb={},Nb={},kb={};var Ob,Pb,Qb,Rb,Sb,Tb,Ub,Vb,Wb,Xb,Yb,Zb,$b,ac,bc,cc,dc,ec,fc,gc,hc,ic,jc,kc,lc,mc,nc,oc,pc,qc,rc,sc,tc,uc,vc,wc,xc,yc,zc,Ac,Bc,Cc,Dc,Ec,Fc,Gc,Hc,Ic,Jc,Kc,Lc,Mc,Nc,Oc,Pc,Qc,Rc,Sc,Tc,Uc,Vc,Wc,Xc,Yc,Zc,$c,ad,bd,cd,dd,ed,fd,gd,hd,id,jd,kd,ld,md,nd,od,pd,qd,rd,sd,td,ud,vd,wd,xd,yd,Za,zd,Ad,Bd,Cd,Dd,Ed,Fd,Gd,Hd,Id,Jd,$a,Kd,Ld,Md,Nd,Od,Pd,Qd,Rd,Sd,Td,Ud,Vd,Wd,Xd,Yd,Zd,$d,ae,be,ce,de,ee,fe,ge,he,ie,je,ke,le,me,ne,oe,pe,qe,re,se,te,ue,ve,we,xe,ye,ze,Ae,Be,Ce,De,Ee,Fe,Ge,He,Ie,Je,Ke,Le,Me,Ne,Oe,Pe,Qe,Re,Se,
Te,Ue,Ve,We,Xe,Ye,Ze,$e,af,bf,cf,df,ef,ff,gf,hf,jf,kf,lf,mf,nf,of,pf,qf,rf,sf,tf,uf,vf,wf,xf,yf,zf,Af,Bf,Cf,Df,Ef,Ff,Gf,Hf,If,Jf,Kf;
(function(){var a=function(a){return{toString:function(){return a}}};Ob=a("");Pb=a("");Qb="";Rb=a("");Sb=a("");Tb=a("");Ub=a("");Vb=a("");Wb=a("");Xb=a("");Yb=a("");Zb=a("0");$b=a("1");ac=a("");bc=a("");cc=a("");
dc=a("");ec=a("");fc=a("");gc=a("");hc=a("");ic=a("");jc=a("");kc=a("");lc=a("");mc=a("");nc=a("");oc=a("");pc=a("");qc=a("");
rc=a("");sc=a("");tc=a("");uc=a("");vc=a("");wc=a("");xc=a("");yc=a("");zc=a("");Ac=a("");Bc=a("");Cc=a("");Dc=a("");Ec=a("");Fc=a("");Gc=a("");Hc=a("");
Ic=a("");Jc=a("");Kc=a("");Lc=a("");Mc=a("");Nc=a("");Oc=a("");Pc=a("");Qc=a("");Rc=a("");Sc=a("");Tc=a("");Uc=a("");Vc=a("");Wc=a("");Xc=a("");Yc=a("");
Zc=a("");$c=a("");ad=a("");bd=a("");cd=a("");dd=a("");ed=a("");fd=a("");gd=a("");hd=a("");id=a("");jd=a("");kd=a("");ld=a("");md=a("");nd=a("");
od=a("");pd=a("");qd=a("");rd=a("");sd=a("");td=a("");ud=a("");vd=a("");wd=a("");xd=a("");yd=a("");Za=a("2");zd=a("");Ad=a("42");Bd=a("43");Cd=a("");Dd=a("");
Ed=a("");Fd=a("");Gd=a("");Hd=a("");Id=a("");Jd=a("");$a=a("3");Kd=a("");Ld=a("");Md=a("");Nd=a("");Od=a("");Pd=a("");Qd=a("");Rd=a("");Sd=a("");Td=a("");Ud=a("");Vd=a("");Wd=a("");
Xd=a("");Yd=a("");Zd=a("");$d=a("");ae=a("");be=a("");ce=a("");de=a("");ee=a("");fe=a("");ge=a("");he=a("");ie=a("");je=a("");ke=a("");le=a("");me=a("");ne=a("");oe=a("");pe=a("");
qe=a("");re=a("");se=a("");te=a("");ue=a("");ve=a("");we=a("");xe=a("");ye=a("");ze=a("");Ae=a("");Be=a("");Ce=a("");De=a("");Ee=a("");Fe=a("");Ge=a("");He=a("");Ie=a("");
Je=a("");Ke=a("");Le=a("");Me=a("");Ne=a("");Oe=a("");Pe=a("");Qe=a("");Re=a("");Se=a("");Te=a("");Ue=a("");Ve=a("");We=a("");Xe=a("5");Ye=
a("");Ze=a("");$e=a("");af=a("");bf=a("");cf=a("");df=a("");ef=a("");ff=a("");gf=a("");hf=a("");jf=a("");kf=a("");lf=a("");mf=a("");nf=a("");of=a("");
pf=a("");qf=a("");rf=a("");sf=a("");tf=a("");uf="";vf=a("");wf=a("");xf=a("");yf=a("");zf=a("");Af=a("");Bf=a("");Cf=a("");Df=a("");Ef=a("");Ff=a("");Gf=
a("");Hf=a("");If=a("");Jf=a("");Kf=a("")})();var Fb=function(a,b){V(a,b)},Lf=function(){},R=function(a){return"function"==typeof a},ab=function(a){return"[object Array]"==Object.prototype.toString.call(Object(a))},Mf=function(a){return"number"==Hb(a)&&!isNaN(a)},Nf=function(a){return/^[0-9]+$/.test(a)},nb=function(a){return"string"==Hb(a)},Of=function(a,b){if(Array.prototype.indexOf){var c=a.indexOf(b);return"number"==typeof c?c:-1}for(var d=0;d<a.length;d++)if(a[d]===b)return d;return-1},Pf=function(a,b){if(a&&ab(a)&&0!=a.length)for(var c=
0;c<a.length;c++)if(a[c]&&b(a[c]))return a[c]},Ba=function(a){return a?a.replace(/^\s+|\s+$/g,""):""},W=function(a){return Math.round(Number(a))||0},Oa=function(a){return"false"==String(a).toLowerCase()?!1:!!a},Qf=function(a){var b=[];if(ab(a))for(var c=0;c<a.length;c++)b.push(String(a[c]));return b},Y=function(){return new Date},Ga=function(a,b){if(!Mf(a)||!Mf(b)||a>b)a=0,b=2147483647;return Math.floor(Math.random()*(b-a+1)+a)},Rf=function(){this.prefix="gtm.";this.values={}};
Rf.prototype.set=function(a,b){this.values[this.prefix+a]=b};Rf.prototype.get=function(a){return this.values[this.prefix+a]};Rf.prototype.contains=function(a){return void 0!==this.get(a)};
var Sf=function(a,b,c){try{if(!a[Zd])return a[Za](a,b||Lf,c||Lf);c&&c()}catch(d){}return!1},Tf=function(a,b){function c(b,c){a.contains(b)||a.set(b,[]);a.get(b).push(c)}for(var d=Ba(b).split("&"),e=0;e<d.length;e++)if(d[e]){var f=d[e].indexOf("=");0>f?c(d[e],"1"):c(d[e].substring(0,f),d[e].substring(f+1))}},Uf=function(a){var b=a?a.length:0;return 0<b?a[b-1]:""},Vf=function(a){var b=Ha.f;return function(){return a(b)}},Wf=function(a){for(var b=0;b<a.length;b++)a[b]()},Ka=function(){return"gtm"+Xf()},
Xf=function(){var a=sb.sequence||0;sb.sequence=a+1;return a},Na=function(a,b,c){return a&&a.hasOwnProperty(b)?a[b]:c},Yf=function(a){return null!==a&&void 0!==a&&void 0!==a.length},Zf=function(a,b){0==b?a.hc=!0:a.ma=!0;var c=a.i;a.G&&(a.G.yb[c]=b);Mb[c]&&(Mb[c].state=b)},$f=function(a,b){return"function"!=typeof String.prototype.startsWith?0===a.indexOf(b):a.startsWith(b)},ag=function(a,b){a.sort(function(a,d){return b(a,d)?-1:b(d,a)?1:0})};var y=window,K=document,gg=navigator,hb=function(a,b){var c=y[a];y[a]=void 0===c?b:c;return y[a]},ib=function(a,b,c,d){return(d||"http:"!=y.location.protocol?a:b)+c},hg=function(a){var b=K.getElementsByTagName("script")[0]||K.body||K.head;b.parentNode.insertBefore(a,b)},ub=function(a,b){b&&(a.addEventListener?a.onload=b:a.onreadystatechange=function(){a.readyState in{loaded:1,complete:1}&&(a.onreadystatechange=null,b())})},u=function(a,b,c){var d=K.createElement("script");d.type="text/javascript";
d.async=!0;d.src=a;ub(d,b);c&&(d.onerror=c);hg(d);return d},Xa=function(a,b){var c=K.createElement("iframe");c.height="0";c.width="0";c.style.display="none";c.style.visibility="hidden";hg(c);ub(c,b);void 0!==a&&(c.src=a);return c},G=function(a,b,c){var d=new Image(1,1);d.onload=function(){d.onload=null;b&&b()};d.onerror=function(){d.onerror=null;c&&c()};d.src=a},va=function(a,b,c,d){a.addEventListener?a.addEventListener(b,c,!!d):a.attachEvent&&a.attachEvent("on"+b,c)},ra=function(a,b,c,d){a.removeEventListener?
a.removeEventListener(b,c,!!d):a.detachEvent&&a.detachEvent("on"+b,c)},w=function(a){y.setTimeout(a,0)},ig=!1,jg=[],kg=function(a){if(!ig){var b=K.createEventObject,c="complete"==K.readyState,d="interactive"==K.readyState;if(!a||"readystatechange"!=a.type||c||!b&&d){ig=!0;for(var e=0;e<jg.length;e++)w(jg[e])}jg.push=function(){for(var a=0;a<arguments.length;a++)w(arguments[a]);return 0}}},lg=0,mg=function(){if(!ig&&140>lg){lg++;try{K.documentElement.doScroll("left"),kg()}catch(a){y.setTimeout(mg,
50)}}},ha=function(a){var b=K.getElementById(a);if(b&&za(b,"id")!=a)for(var c=1;c<document.all[a].length;c++)if(za(document.all[a][c],"id")==a)return document.all[a][c];return b},za=function(a,b){return a&&b&&a.attributes&&a.attributes[b]?a.attributes[b].value:null},ng=function(a){return a.target||a.srcElement||{}},Aa=function(a){var b=a.innerText||a.textContent||"";b&&" "!=b&&(b=b.replace(/^[\s\xa0]+|[\s\xa0]+$/g,""));b&&(b=b.replace(/(\xa0+|\s{2,}|\n|\r\t)/g," "));return b},zb=function(a){var b=
K.createElement("div");b.innerHTML="A<div>"+a+"</div>";b=b.lastChild;for(var c=[];b.firstChild;)c.push(b.removeChild(b.firstChild));return c},og=function(a,b,c){c=c||100;for(var d={},e=0;e<b.length;e++)d[b[e]]=!0;var f=a;for(e=0;f&&e<=c;e++){if(d[String(f.tagName).toLowerCase()])return f;f=f.parentElement}return null},pg=!1,qg=[],rg=function(){if(!pg){pg=!0;for(var a=0;a<qg.length;a++)w(qg[a])}},sg=function(a){a=a||y;var b=a.location.href,c=b.indexOf("#");return 0>c?"":b.substring(c+1)},tb=function(a){window.console&&
window.console.log&&window.console.log(a)};var tg=function(a,b){for(var c=a.split("&"),d=0;d<c.length;d++){var e=c[d].split("=");if(decodeURIComponent(e[0]).replace(/\+/g," ")==b)return decodeURIComponent(e.slice(1).join("=")).replace(/\+/g," ")}},U=function(a,b,c,d,e){var f,g=(a.protocol.replace(":","")||y.location.protocol.replace(":","")).toLowerCase();b&&(b=String(b).toLowerCase());switch(b){case "protocol":f=g;break;case "host":f=(a.hostname||y.location.hostname).split(":")[0].toLowerCase();if(c){var h=/^www\d*\./.exec(f);h&&h[0]&&(f=
f.substr(h[0].length))}break;case "port":f=String(1*(a.hostname?a.port:y.location.port)||("http"==g?80:"https"==g?443:""));break;case "path":f="/"==a.pathname.substr(0,1)?a.pathname:"/"+a.pathname;var k=f.split("/");0<=Of(d||[],k[k.length-1])&&(k[k.length-1]="");f=k.join("/");break;case "query":f=a.search.replace("?","");e&&(f=tg(f,e));break;case "fragment":f=a.hash.replace("#","");break;default:f=a&&a.href}return f},Da=function(a){var b="";if(a&&a.href){var c=a.href.indexOf("#");b=0>c?a.href:a.href.substr(0,
c)}return b},T=function(a){var b=K.createElement("a");a&&(b.href=a);return b};var wa=function(a,b){var c=function(){};c.prototype=a.prototype;var d=new c;a.apply(d,Array.prototype.slice.call(arguments,1));return d};var ob=function(a){return encodeURIComponent(a)},ea=function(a){var b=["veinteractive.com","ve-interactive.cn"];if(!a)return!1;var c=U(T(a),"host");if(!c)return!1;for(var d=0;b&&d<b.length;d++){var e=b[d]&&b[d].toLowerCase();if(e){var f=c.length-e.length;0<f&&"."!=e.charAt(0)&&(f--,e="."+e);if(0<=f&&c.indexOf(e,f)==f)return!0}}return!1};
var P=function(a,b,c){for(var d={},e=!1,f=0;a&&f<a.length;f++)a[f]&&a[f].hasOwnProperty(b)&&a[f].hasOwnProperty(c)&&(d[a[f][b]]=a[f][c],e=!0);return e?d:null},Ia=function(a,b){V(a,b)},Pa=function(a){return W(a)},Ab=function(a,b){return Of(a,b)};/*
 Copyright (c) 2014 Derek Brans, MIT license https://github.com/krux/postscribe/blob/master/LICENSE. Portions derived from simplehtmlparser, which is licensed under the Apache License, Version 2.0 */
var vg={event:function(a){var b=a[1];if(nb(b)&&!(3<a.length)){var c;if(2<a.length){if(!La(a[2]))return;c=a[2]}var d=c,e={event:b};d&&(d=V(d,void 0),e.eventModel=d,e.eventCallback=d.eventCallback);return e}},set:function(a){var b;2==a.length&&La(a[1])?b=V(a[1],void 0):3==a.length&&nb(a[1])&&(b={},b[a[1]]=a[2]);if(b)return b._clear=!0,b},js:function(a){if(2==a.length&&a[1].getTime)return{event:"gtm.js","gtm.start":a[1].getTime()}}};var wg=new Rf,xg={},zg={set:function(a,b){V(yg(a,b),xg)},get:function(a){return Z(a,2)},reset:function(){wg=new Rf;xg={}}},Z=function(a,b){return 2!=b?wg.get(a):Ag(a)},Ag=function(a){for(var b=a.split("."),c=0,d=xg.eventModel;void 0!==d&&c<b.length;c++){if(null===d)return!1;d=d[b[c]]}if(void 0!==d||1<c)return d;var e=xg;for(c=0;c<b.length;c++){if(null===e)return!1;if(void 0===e[b[c]])return;e=e[b[c]]}return e},Bg=function(a,b){wg.set(a,b);V(yg(a,b),xg)},yg=function(a,b){for(var c={},d=c,e=a.split("."),
f=0;f<e.length-1;f++)d=d[e[f]]={};d[e[e.length-1]]=b;return c};var Cg=!1,Dg=!1;var Ja=function(a){var b=y;b.GoogleAnalyticsObject||(b.GoogleAnalyticsObject=a||"ga");var c=b.GoogleAnalyticsObject;if(!b[c]){var d=function(){d.q=d.q||[];d.q.push(arguments)};d.l=Number(Y());b[c]=d}return b[c]},Qa=function(){var a=y;return a.GoogleAnalyticsObject&&a[a.GoogleAnalyticsObject]},Ra=function(a,b,c,d){b=String(b).replace(/\s+/g,"").split(",");var e=Qa();e(a+"require","linker");e(a+"linker:autoLink",b,c,d)};var Eg=Math.random(),Fg="0.050000">Eg;
var Gg=function(a,b){if(Fg){var c=Lb,d=function(a,b){b&&(c+=a+encodeURIComponent(b))};d("&v=","t");d("&n=",a);d("&s=",b&&b.state);d("&h=",b&&b.hideLatency);d("&g=",b&&b.gaLatency);d("&p=",b&&b.loadBy);d("&o=",b&&b.timeout);d("&l=",Y().getTime()-W(Kb));c+="&sr=0.050000";d("&ps=",Eg);d("&cb=",Ga());G(c)}},Hg=Lf,Ig=function(){var a=!1;
};var Kg=function(a){var b=sb.zones;return b?b.checkState(Ha.f,a):Jg},qb=function(a){var b=sb.zones;!b&&a&&(b=sb.zones=a());return b},Jg={active:!0,isWhitelisted:function(){return!0}};var Lg=Lf,Mg=[],Ng=!1,Og=function(a){return y["dataLayer"].push(a)},Pg=function(a){var b=!1;return function(){!b&&R(a)&&w(Vf(a));b=!0}},Yg=function(){for(var a=!1;!Ng&&0<Mg.length;){Ng=!0;delete xg.eventModel;var b=Mg.shift();if(R(b))try{b.call(zg)}catch(Ma){}else if(ab(b))a:{var c=b;if(nb(c[0])){for(var d=c[0].split("."),e=d.pop(),f=c.slice(1),g=xg,h=0;h<d.length;h++){if(void 0===g[d[h]])break a;g=g[d[h]]}try{g[e].apply(g,f)}catch(Ma){}}}else{var k=b;if(k&&("[object Arguments]"==Object.prototype.toString.call(k)||
Object.prototype.hasOwnProperty.call(k,"callee"))){a:{var l=b;if(l.length&&nb(l[0])){var m=vg[l[0]];if(m){b=m(l);break a}}b=void 0}if(!b){Ng=!1;continue}}var n=void 0,p=void 0,r=b,t=r._clear;for(p in r)r.hasOwnProperty(p)&&"_clear"!==p&&(t&&Bg(p,void 0),Bg(p,r[p]));var v=!1,z=r.event;if(z){r.hasOwnProperty("gtm.uniqueEventId")||(r["gtm.uniqueEventId"]=Xf(),Bg("gtm.uniqueEventId",r["gtm.uniqueEventId"]));n=r["gtm.uniqueEventId"];Ca=z;var J=Kg(n);if(J.active){var F=Pg(r.eventCallback),E=r.eventTimeout;
E&&y.setTimeout(F,Number(E));v=Lg(n,z,J.isWhitelisted,F,r.eventReporter)}}Kb||(Kb=r["gtm.start"])&&Hg();var L,B=r,D=n,A=z,C=xg;Ca=null;a=v||a}Ng=!1}return!a},Zg=function(){var a=Yg();try{var b=y["dataLayer"].hide;if(b&&void 0!==b[Ha.f]&&b.end){b[Ha.f]=!1;var c=!0,d;for(d in b)if(b.hasOwnProperty(d)&&!0===b[d]){c=!1;break}c&&(b.end(),b.end=null)}}catch(e){}return a},$g=function(){var a=hb("dataLayer",[]),b=hb("google_tag_manager",{});b=b["dataLayer"]=b["dataLayer"]||{};jg.push(function(){b.gtmDom||(b.gtmDom=!0,a.push({event:"gtm.dom"}))});qg.push(function(){b.gtmLoad||
(b.gtmLoad=!0,a.push({event:"gtm.load"}))});var c=a.push;a.push=function(){var b=[].slice.call(arguments,0);c.apply(a,b);for(Mg.push.apply(Mg,b);300<this.length;)this.shift();return Yg()};Mg.push.apply(Mg,a.slice(0));w(Zg)};var ah,bh,ch;
var Ea=function(a,b){var c={"gtm.element":a,"gtm.elementClasses":a.className,"gtm.elementId":a["for"]||za(a,"id")||"","gtm.elementTarget":a.formTarget||a.target||""};if(b&&eh)if("LINK_CLICK"==b)c["gtm.elementUrl"]=a.href;else if("FORM_SUBMIT"==b){var d=a.action;d&&d.tagName&&(d=a.cloneNode(!1).action);c["gtm.elementUrl"]=d}c.hasOwnProperty("gtm.elementUrl")||(c["gtm.elementUrl"]=(a.attributes&&a.attributes.formaction?a.formAction:"")||a.action||a.href||a.src||a.code||a.codebase||"");return c},th=
function(a){sb.hasOwnProperty("autoEventsSettings")||(sb.autoEventsSettings={});var b=sb.autoEventsSettings;b.hasOwnProperty(a)||(b[a]={});return b[a]},pa=function(a,b,c){th(a)[b]=c},gb=function(a,b,c,d){var e=th(a),f=Na(e,b,d);e[b]=c(f)},ta=function(a,b,c){var d=th(a);return Na(d,b,c)},qa=function(a){return!!ta(a,"init",!1)},ua=function(a){pa(a,"init",!0)},uh=function(){};var vh=/(^|\.)doubleclick\.net$/i,wh=/^(www\.)?google(\.com?)?(\.[a-z]{2})?$/,Fa=function(a,b,c){for(var d=String(b||K.cookie).split(";"),e=[],f=0;f<d.length;f++){var g=d[f].split("="),h=Ba(g[0]);if(h&&h==a){var k=Ba(g.slice(1).join("="));k&&!1!==c&&(k=decodeURIComponent(k));e.push(k)}}return e},yh=function(a,b,c,d,e,f){f&&(b=encodeURIComponent(b));var g=a+"="+b+"; ";c&&(g+="path="+c+"; ");e&&(g+="expires="+e.toGMTString()+"; ");var h;h="auto"==d?xh():[d||"none"];for(var k=0;k<h.length;k++){var l=
g,m=h[k],n=c;if(vh.test(y.location.hostname)||"/"==n&&wh.test(m))break;"none"!=h[k]&&(l+="domain="+h[k]+";");var p=K.cookie;K.cookie=l;if(p!=K.cookie||0<=Of(Fa(a),b))return!0}return!1},zh=function(a){if("none"==a)return 0;0==a.indexOf(".")&&(a=a.substr(1));return a.split(".").length},Ah=function(a){var b=a;b?(1<b.length&&b.lastIndexOf("/")==b.length-1&&(b=b.substr(0,b.length-1)),0!=b.indexOf("/")&&(b="/"+b),a=b):a="/";return"/"==a?1:a.split("/").length},xh=function(){var a=U(y.location,"host",!0).split(".");
if(4==a.length&&/^[0-9]*$/.exec(a[3]))return["none"];for(var b=[],c=a.length-2;0<=c;c--)b.push(a.slice(c).join("."));b.push("none");return b};var fa=function(a){var b=K;return Bh?b.querySelectorAll(a):null},Ch=!1;if(K.querySelectorAll)try{var Dh=K.querySelectorAll(":root");Dh&&1==Dh.length&&Dh[0]==K.documentElement&&(Ch=!0)}catch(a){}var Bh=Ch;var Eh=function(a){for(var b=[],c=K.cookie.split(";"),d=new RegExp("^\\s*"+a+"=\\s*(.*?)\\s*$"),e=0;e<c.length;e++){var f=c[e].match(d);f&&b.push(f[1])}var g=[];if(!b||0==b.length)return g;for(var h=0;h<b.length;h++){var k=b[h].split(".");3==k.length&&"GCL"==k[0]&&k[1]&&g.push(k[2])}return g};var Fh=/^\w+$/,Gh=/^[\w-]+$/,Hh=/^\d+\.fls\.doubleclick\.net$/;function Ih(a){return a&&"string"==typeof a&&a.match(Fh)?a:"_gcl"}function Jh(a){if(a){if("string"==typeof a){var b=Ih(a);return{na:b,la:b}}if(a&&"object"==typeof a)return{na:Ih(a.dc),la:Ih(a.aw)}}return{na:"_gcl",la:"_gcl"}}function Kh(a){var b=T(y.location.href),c=U(b,"host",!1);if(c&&c.match(Hh)){var d=U(b,"path").split(a+"=");if(1<d.length)return d[1].split(";")[0].split("?")[0]}}
function Lh(a){return a.filter(function(a){return Gh.test(a)})}var Nh=function(a){var b=Kh("gclaw");if(b)return b.split(".");var c=Jh(a);if("_gcl"==c.la){var d=Mh();if(d&&(null==d.L||"aw.ds"==d.L))return[d.qa]}return Lh(Eh(c.la+"_aw"))},Oh=function(a){var b=Kh("gcldc");if(b)return b.split(".");var c=Jh(a);if("_gcl"==c.na){var d=Mh();if(d&&("ds"==d.L||"aw.ds"==d.L))return[d.qa]}return Lh(Eh(c.na+"_dc"))};
function Mh(){var a=T(y.location.href),b=U(a,"query",!1,void 0,"gclid"),c=U(a,"query",!1,void 0,"gclsrc");if(!b||!c){var d=U(a,"fragment");b=b||tg(d,"gclid");c=c||tg(d,"gclsrc")}return void 0!==b&&b.match(Gh)?{qa:b,L:c}:null}
var Ya=function(a,b,c){var d=Jh(a);c=c||"auto";b=b||"/";var e=Mh();if(null!==e){var f=(new Date).getTime(),g=new Date(f+7776E6),h=["GCL",Math.round(f/1E3),e.qa].join(".");e.L&&"aw.ds"!=e.L||yh(d.la+"_aw",h,b,c,g,!0);"aw.ds"!=e.L&&"ds"!=e.L||yh(d.na+"_dc",h,b,c,g,!0)}},Ph=function(){var a=Kh("gac");if(a)return decodeURIComponent(a);for(var b=[],c=K.cookie.split(";"),d=/^\s*_gac_(UA-\d+-\d+)=\s*(.+?)\s*$/,e=0;e<c.length;e++){var f=c[e].match(d);f&&b.push({Ab:f[1],value:f[2]})}var g={};if(b&&b.length)for(var h=
0;h<b.length;h++){var k=b[h].value.split(".");"1"==k[0]&&3==k.length&&k[1]&&(g[b[h].Ab]||(g[b[h].Ab]=[]),g[b[h].Ab].push({timestamp:k[1],qa:k[2]}))}var l=[],m;for(m in g)if(g.hasOwnProperty(m)){for(var n=[],p=g[m],r=0;r<p.length;r++)n.push(p[r].qa);n=Lh(n);n.length&&l.push(m+":"+n.join(","))}return l.join(";")};var Qh;a:{Qh="G"}var Rh={"":"n",UA:"u",AW:"a",DC:"d",GTM:Qh},ya=function(a){var b=Ha.f.split("-"),c=b[0].toUpperCase();return(Rh[c]||"i")+"2r"+(a&&"GTM"===c?b[1]:"")};var lb=new String("undefined"),Vh=function(a){this.resolve=function(b){for(var c=[],d=0;d<a.length;d++)c.push(a[d]===lb?b:a[d]);return c.join("")}};Vh.prototype.toString=function(){return this.resolve("undefined")};Vh.prototype.valueOf=Vh.prototype.toString;var Wh={},Xh=function(a,b){var c=Xf();Wh[c]=[a,b];return c},Yh=function(a){var b=a?0:1;return function(a){var c=Wh[a];if(c&&R(c[b]))c[b]();Wh[a]=void 0}};var Zh={},$h,ai;
var ji=function(){};
var la=function(){var a=K.body,b=K.documentElement||a&&a.parentElement,c,d;if(K.compatMode&&"BackCompat"!==K.compatMode)c=b?b.clientHeight:0,d=b?b.clientWidth:0;else{var e=function(a,b){return a&&b?Math.min(a,b):Math.max(a,b)};c=e(b?b.clientHeight:0,a?a.clientHeight:0);d=e(b?b.clientWidth:0,a?a.clientWidth:0)}return{sb:d,rb:c}},ki=function(a){var b=la(),c=b.rb,d=b.sb,e=a.getBoundingClientRect(),f=e.bottom-e.top,g=e.right-e.left;return f&&g?(1-Math.min((Math.max(0-e.left,0)+Math.max(e.right-d,0))/
g,1))*(1-Math.min((Math.max(0-e.top,0)+Math.max(e.bottom-c,0))/f,1)):0},li=function(a){if(K.hidden)return!0;var b=a.getBoundingClientRect();if(b.top==b.bottom||b.left==b.right||!y.getComputedStyle)return!0;var c=y.getComputedStyle(a,null);if("hidden"===c.visibility)return!0;for(var d=a,e=c;d;){if("none"===e.display)return!0;var f=e.opacity,g=e.filter;if(void 0!==g){var h=g.indexOf("opacity(");0<=h&&(g=g.substring(h+8,g.indexOf(")",h)),"%"==g.charAt(g.length-1)&&(g=g.substring(0,g.length-1)),f=Math.min(g,
f))}if(void 0!==f&&0>=f)return!0;(d=d.parentElement)&&(e=y.getComputedStyle(d,null))}return!1};var bb=function(a,b,c,d){va(a,b,c,d)},ka=function(a,b){return y.setTimeout(a,b)},ba=function(a,b,c){u(a,b,c)},db={},Sa=function(a,b,c){var d=db[a];if(void 0===d){var e=function(a,b){return function(){a.status=b;for(var c=2==b?a.wb:a.cb,d=0;d<c.length;d++)y.setTimeout(c[d],0)}};d={status:1,wb:[],cb:[],ec:void 0};d.qd=u(a,e(d,2),e(d,3));db[a]=d}0===d.status&&(d.ec(),d.status=2);2===d.status?b&&b():3===d.status?c&&c():1===d.status&&(b&&d.wb.push(b),c&&d.cb.push(c))},ri=function(a,b){db[a]={status:0,
wb:[],cb:[],ec:b,qd:null}},ca=function(){return y.location.href},cb=function(a){return U(T(a),"fragment")},S=function(a,b){return Z(a,b||2)},na=function(a,b,c){b&&(a.eventCallback=b,c&&(a.eventTimeout=c));return Og(a)},aa=function(a,b){y[a]=b},q=function(a,b,c){var d=y;b&&(void 0===d[a]||c&&!d[a])&&(d[a]=b);return d[a]},eb=function(a,b){return og(a,b,100)},x=function(a,b,c,d){var e=!d&&"http:"==y.location.protocol;e&&(e=2!==pb());return(e?b:a)+c},vb=function(a){ig?a():jg.push(a)};
var ia=function(a){var b=0;b=ki(a);return b},Cb=function(a){},ja=function(a){var b=!1;b=li(a);return b},fb=function(a,b){return Pf(a,
b)},oa=function(a,b,c,d){gb(a,b,c,d)},sa=function(a,b,c){return ta(a,b,c)};
var Eb=void 0,Va=function(a){if(!Eb){var b=function(){var a=K.body;if(a)if(q("MutationObserver"))(new MutationObserver(function(){for(var a=0;a<Eb.length;a++)w(Eb[a])})).observe(a,{childList:!0,subtree:!0});else{var b=!1;bb(a,"DOMNodeInserted",function(){b||(b=!0,w(function(){b=!1;for(var a=0;a<Eb.length;a++)w(Eb[a])}))})}};Eb=[];K.body?b():w(b)}Eb.push(a)},pb=function(){var a;a="www.googletagmanager.com/gtm.js";for(var b="https://"+a,c="http://"+a,d=1,e=K.getElementsByTagName("script"),f=0;f<e.length&&100>f;f++){var g=
e[f].src;if(g){g=g.toLowerCase();if($f(g,c))return 3;1===d&&$f(g,b)&&(d=2)}}return d};var Bb=function(){return Qa()};
var rb=function(a){var b="www.googletagmanager.com/gtm.js?id="+encodeURIComponent(a)+"&l=dataLayer";u(x("https://","http://",b),void 0,void 0)};var xb=function(a,b,c){a instanceof Vh&&(a=a.resolve(Xh(b,c)),b=Lf);return{hb:a,w:b}};var si=new RegExp(/^(.*\.)?(google|youtube|blogger|withgoogle)(\.com?)?(\.[a-z]{2})?\.?$/),ti={customPixels:["nonGooglePixels"],html:["customScripts","customPixels","nonGooglePixels","nonGoogleScripts","nonGoogleIframes"],customScripts:["html","customPixels","nonGooglePixels","nonGoogleScripts","nonGoogleIframes"],nonGooglePixels:[],nonGoogleScripts:["nonGooglePixels"],nonGoogleIframes:["nonGooglePixels"]},ui={customPixels:["customScripts","html"],html:["customScripts"],customScripts:["html"],nonGooglePixels:["customPixels",
"customScripts","html","nonGoogleScripts","nonGoogleIframes"],nonGoogleScripts:["customScripts","html"],nonGoogleIframes:["customScripts","html","nonGoogleScripts"]},vi=function(a,b){for(var c=[],d=0;d<a.length;d++)c.push(a[d]),c.push.apply(c,b[a[d]]||[]);return c},Rg=function(a){var b=Z("gtm.whitelist");
var c=b&&vi(Qf(b),ti),d=Z("gtm.blacklist")||Z("tagTypeBlacklist")||[];si.test(y.location&&y.location.hostname)&&(d=Qf(d),d.push("nonGooglePixels","nonGoogleScripts"));var e=d&&vi(Qf(d),ui),f={};return function(g){var h=g&&g[Za];if(!h)return!0;if(void 0!==f[h.a])return f[h.a];var k=a(h.a);if(b){var l;if(l=k)a:{if(0>Of(c,h.a))if(h.b&&0<h.b.length)for(var m=0;m<h.b.length;m++){if(0>
Of(c,h.b[m])){l=!1;break a}}else{l=!1;break a}l=!0}k=l}var n=!1;if(d){var p;if(!(p=0<=Of(e,h.a)))a:{for(var r=h.b||[],t=new Rf,v=0;v<e.length;v++)t.set(e[v],!0);for(v=0;v<r.length;v++)if(t.get(r[v])){p=!0;break a}p=!1}n=p}return f[h.a]=!k||n}};var wi=void 0,xi="",yi=0,zi=void 0,_et=function(a){var b,c=Z("gtm.element"),d=Z("event"),e=Number(Y());wi===c&&xi===d&&yi>e-250?b=zi:(zi=b=c?Aa(c):"",wi=c,xi=d);yi=e;return b?b:a[Xc]};_et.a="et";_et.b=["google"];var _eu=function(a){var b=String(Z("gtm.elementUrl")||a[Xc]||""),c=T(b);return b};_eu.a="eu";_eu.b=["google"];var Ai=function(a,b){this.h=a;this.s=b};Ai.prototype.toString=function(){var a=""+this.h;1<this.s&&(a=a+"-"+this.s);return a};var Bi=function(a,b){this.vb=a;this.Ma=b};Bi.prototype.toString=function(){return""+this.Ma+"."+this.vb};var Ei=function(a,b){var c=new Ci(null,a,b);Di(c);return c},Ci=function(a,b,c){this.Pb=Math.floor(Y().getTime()/864E5);this.Ka=b||"auto";this.ua=c||"/";var d=zh(this.Ka),e=Ah(this.ua);this.N=a||new Ai(d,e);this.m=[];this.I=new Rf},Gi=function(a,b,c){b&&(""==c.vb?Fi(a,b):(a.I.contains(b)||a.m.push(b),a.I.set(b,c)))},Hi=function(a,b){for(var c=0;c<b.length;c++)Gi(a,b[c][0],b[c][1])},Fi=function(a,b){var c=Of(a.m,b);0<=c&&a.m.splice(c,1);a.I.set(b,void 0)},Ii=function(a){for(var b=[],c=0;c<a.m.length;c++){var d=
a.m[c];b.push([d,a.I.get(d)])}return b},Ji=function(a){for(var b=0,c=0;c<a.m.length;c++)b=Math.max(b,a.I.get(a.m[c]).Ma);return 864E5*b};Ci.prototype.toString=function(){if(0==this.m.length)return"";for(var a=[],b=0;b<this.m.length;b++){var c=this.m[b];a.push(""+c+"."+this.I.get(c).toString())}return"GAX1."+this.N.toString()+"."+a.join("!")};
var Ki=function(a,b){for(var c=new Date,d=Ah(a.ua),e=[],f=0;f<a.m.length;f++){var g=a.m[f];a.I.get(g).Ma<a.Pb&&e.push(g)}for(f=0;f<e.length;f++)Fi(a,e[f]);if(a.m.length>(b||10))return!1;c.setTime(Ji(a));if("auto"!=a.Ka)return yh("_gaexp",a.toString(),a.ua,a.Ka,c);for(var h=xh(),k=0;k<h.length;k++)if("none"!=h[k]&&(a.N=new Ai(zh(h[k]),d),yh("_gaexp",a.toString(),a.ua,h[k],c)))return!0;return!1},Di=function(a){for(var b=a.N.h,c=a.N.s,d=Fa("_gaexp"),e=[],f=0;f<d.length;f++){var g=Li(a,d[f]);g&&e.push(g)}ag(e,
function(a,d){var e=a.N,f=d.N;return e.h==f.h&&e.s==f.s?!1:e.h==b&&e.s==c?!0:f.h==b&&f.s==c?!1:e.h==b?f.h!=b||e.s<f.s:f.h==b?!1:e.s==c?f.h!=b&&(f.s!=c||e.h<f.h):f.s==c?!1:e.h<f.h||e.h==f.h&&e.s<f.s});a.N=0<e.length?e[0].N:new Ai(b,c);for(f=e.length-1;0<=f;f--)Hi(a,Ii(e[f]))},Li=function(a,b){var c=b.match(/GAX1\.([^.]+).(.*)/);if(c){var d;a:{var e=(c[1]||"").split("-");if(!(0==e.length||2<e.length)){var f=Ba(e[0]);if(0!=f.length){var g=2==e.length?Ba(e[1]):"1";if(Nf(f)&&Nf(g)){d=new Ai(W(f),W(g));
break a}}}d=void 0}if(d){for(var h=new Ci(d,a.Ka,a.ua),k=(c[2]||"").split("!"),l=0;l<k.length;l++){var m=k[l].split(".");if(3==m.length){if(!Nf(m[1]))return;Gi(h,m[0],new Bi(m[2],W(m[1])))}}return h}}};var _f=function(a){var b=String(Z("gtm.referrer")||K.referrer);if(!b)return b;var c=T(b);return b};_f.a="f";_f.b=["google"];var Pi=function(a){var b=y.location,c;(c=a[Mc]?a[Mc]:Z("gtm.url"))&&(b=T(String(c)));var d=b.href,e=d.indexOf("#"),f=0>e?d:d.substr(0,e);return f},_u=Pi;_u.a="u";_u.b=["google"];var _cn=function(a){return 0<=String(a[Zb]).indexOf(String(a[$b]))};_cn.a="cn";_cn.b=["google"];var _eq=function(a){return String(a[Zb])==String(a[$b])};_eq.a="eq";_eq.b=["google"];var _re=function(a){return(new RegExp(a[$b],a[Gd]?"i":void 0)).test(a[Zb])};_re.a="re";_re.b=["google"];
var mj=function(a,b,c,d,e){var f=a+"{"+(b+": "+c+(d?" !important":""))+"}";e&&(f=e+"{"+f+"}");var g=document;if(g.createStyleSheet){var h=jj(g),k=h.rules.length;h.insertRule(f,k);return function(){h.deleteRule?h.deleteRule(k):h.removeRule(k);h.insertRule("x {}",k)}}var l=kj(f,g);lj(l,g);var m=l.parentNode;return function(){m.removeChild(l)}},nj=null,jj=function(a){if(nj)return nj;for(var b=a.styleSheets.length-1;0<=b;b--){var c=a.styleSheets[b],d=c.ownerNode;if(d&&d.parentNode&&"HEAD"==d.parentNode.tagName)return nj=
c}0==a.styleSheets.length&&a.createStyleSheet();return nj=a.styleSheets[0]},kj=function(a,b){var c=(b||document).createElement("style");void 0!==c.cssText?c.cssText=a:c.innerHTML=a;return c},lj=function(a,b){var c=b||document,d=c.getElementsByTagName("head")[0];d||(d=c.createElement("head"),c.body.parentNode.insertBefore(d,c.body));d.appendChild(a)};var uj={},vj=void 0,wj=function(a){var b=uj[a];b||(b={id:a,A:[],pa:0,Bb:null,kb:void 0,qb:!1},uj[a]=b);vj=b},yj=function(a,b,c,d){var e=vj;if(!Bh||!e)return!1;var f={id:e.id+":"+e.A.length,vc:b,fa:[],qc:c,O:a,Za:0,Ua:d||null,Ob:0,oa:!1};e.A.push(f);null===a?(f.oa=!0,b(null)):xj(e);return!0},zj=function(a){var b=mj(a,"visibility","hidden",!0);return function(){R(b)&&b.apply();b=null}},Aj=function(a,b,c,d){var e=b;if(!ig){var f=zj(a.F);jg.push(f);e=function(a,c){var d=b(a,c);f();return d}}return yj(a,
e,c,d)},xj=function(a){if(!a.qb){for(var b=a.pa;b<a.A.length;b++){var c=a.A[b],d=b==a.pa;if(!c.oa&&!Bj(d,c))break;c.oa&&d&&a.pa++}a.A.length>a.pa?(a.Bb||(a.Bb=y.setTimeout(function(){a.Bb=null;xj(a)},80)),ig||a.kb||(a.kb=function(){w(function(){xj(a)})},va(K,"DOMContentLoaded",a.kb))):Cj(a)}},Cj=function(a){for(var b=0;b<a.A.length;b++){var c=a.A[b];if(c.O)for(var d=fa(c.O.F)||[],e=0;e<d.length;e++){var f=d[e];f.gtmProgressiveApplied&&f.gtmProgressiveApplied[c.id]||(Dj(f,c.id),c.fa.push(Ej(f,c.id)))}}},
Bj=function(a,b){var c=[];if(b.O){var d=Fj(b.O,b.id),e=null;b.Ua&&(e=Fj(b.Ua,b.id+"-t"));for(var f=0;f<d.length;f++){var g=d[f],h;if(null!=e&&(h=e.length>f?e[f]:null,!h&&!ig&&(null===b.Ua.v||b.Ob+c.length<b.Ua.v)))break;c.push({element:g,td:h})}}if(!ig&&b.qc&&(!a||null==b.O.v||b.O.v!=b.Za+c.length))return!1;for(var k=0;k<c.length;k++){var l=c[k].element,m=c[k].td,n;b.Za++;Dj(l,b.id);m&&(b.Ob++,n=b.id+"-t",Dj(m,n));var p=b.vc(l,m);R(p)&&b.fa.push(p);b.fa.push(Ej(l,b.id));m&&n&&b.fa.push(Ej(m,n))}if(b.O.v&&
b.O.v==b.Za||ig)b.oa=!0;return!0},Dj=function(a,b){a.gtmProgressiveApplied||(a.gtmProgressiveApplied={});a.gtmProgressiveApplied[b]=!0},Ej=function(a,b){return function(){a.gtmProgressiveApplied&&delete a.gtmProgressiveApplied[b]}},Fj=function(a,b){for(var c=fa(a.F)||[],d=[],e=0;e<c.length;e++){var f=c[e];if(!f.gtmProgressiveApplied||!f.gtmProgressiveApplied[b]){if(a.M&&!Gj(f))break;d.push(f)}}return d},Gj=function(a){if(ig)return!0;for(;a;){if(a.nextSibling)return!0;a=a.parentNode}return!1};var yk=function(a){if(!a)return!1;if(a[Yb]&&ab(a[$b])){for(var b=a[$b],c=0;c<b.length;c++)if(a[$b]=b[c],Sf(a))return!0;return!1}return Sf(a)};var zk=133,Ak=[],Bk=[],Sg=[],Ck=new Rf,Dk=[],Ek=[],qh=[],rh=[],Fk=function(){this.V=[]};Fk.prototype.set=function(a,b){this.V.push([a,b]);return this};Fk.prototype.resolve=function(a,b){for(var c={},d=0;d<this.V.length;d++){var e=Vg(this.V[d][0],a,b),f=Vg(this.V[d][1],a,b);c[e]=f}return c};var Gk=function(a){this.index=a};Gk.prototype.resolve=function(a,b){var c=Sg[this.index];if(c&&!b(c)){var d=c[$a];if(a){if(a.get(d))return;a.set(d,!0)}c=Vg(c,a,b);a&&a.set(d,!1);return Sf(c)}};
var _M=function(a){return new Gk(a)},Hk=function(a){this.resolve=function(b,c){for(var d=[],e=!1,f=0;f<a.length;f++){var g=Vg(Ak[a[f]],b,c);g===lb&&(e=!0);d.push(g)}return e?new Vh(d):d.join("")}},_T=function(a){return new Hk(arguments)},Ik=function(a){function b(b){for(var c=1;c<a.length;c++)if(a[c]==b)return!0;return!1}this.resolve=
function(c,d){var e=Vg(a[0],c,d);if(a[0]instanceof Gk&&b(8)&&b(16)){if(e===lb)return e;var f=Ka();Ck.set(f,e);return'google_tag_manager["'+Ha.f+"\"].macro('"+f+"')"}e=String(e);for(var g=1;g<a.length;g++)e=dk[a[g]](e);return e}},_E=function(a,b){return new Ik(arguments)},Jk=function(a,b){this.D=a;this.ya=b},_R=function(a,b){return new Jk(a,b)};
var Vg=function(a,b,c){var d=a;if(a instanceof Gk||a instanceof Fk||a instanceof Hk||a instanceof Ik)return a.resolve(b,c);if(!(a instanceof Jk))if(ab(a)){d=[];for(var e=0;e<a.length;e++)d[e]=Vg(a[e],b,c)}else if(a&&"object"==typeof a){d={};for(var f in a)a.hasOwnProperty(f)&&(d[f]=Vg(a[f],b,c))}return d},Mk=function(){for(var a=[_eq,__e,'_event','1',_M(0),'gtm.js','6758092_2147479553',__ua,true,'TRACK_PAGEVIEW','UA-101421125-1',false,1,'UA-102875243-1',3,__v,'Click Classes','gtm.elementClasses',_M(1),'btn webform-button--submit button button--primary js-form-submit form-submit','gtm.click','6758092_7','Gởi yêu cầu','TRACK_EVENT',__gas,'GA ID','auto',_M(2),'Click',4,_cn,'Click ID','gtm.elementId',_M(3),'edit-submit-finddoctor','6758092_8','Tìm bác sĩ trong trang',5,'webform-button--submit button button--primary js-form-submit form-submit','6758092_9','Đặt lịch khám','Gởi thông tin',6,_et,'Click Text',_M(4),'Gọi Chúng Tôi','Click hotline','6758092_10',7,'gtm.scrollDepth',_re,'_triggers','gtm.triggers',2,'',_M(5),'(^$|((^|,)6758092_14($|,)))','6758092_14',__paused,'ua',8,'Click on page','6758092_15',9,'edit-subscribe','Đăng kí nhận thông tin','6758092_16',10,'Form Classes',_M(6),'webform-button--next button js-form-submit form-submit','Form ID',_M(7),'edit-next','6758092_17','Click Đặt Lịch Hẹn','Lick Tiếp Kết Thúc Đặt Hẹn Trang 1',11,__sp,'830492231','NONE',__u,'_url',_M(8),12,'6758092_18',__cl,13,'6758092_19',14,'6758092_20',15,'6758092_21',16,'6758092_22',__sdl,'PERCENT','25',17,'6758092_23',18,'6758092_24',19,'6758092_25',20,'Page URL','URL','Page Hostname','HOST','Page Path','PATH',__f,'Referrer','Event','Click Element','gtm.element','Click Target','gtm.elementTarget','Click URL','gtm.elementUrl','Form Element','Form Target','Form URL','Form Text','Scroll Depth Threshold','gtm.scrollThreshold','Scroll Depth Units','gtm.scrollUnits','Scroll Direction','gtm.scrollDirection'],b=[],c=0;c<a.length;c++)b[c]=
Lk(c,a);return b},Lk=function(a,b){var c=b[a],d=c;if(c instanceof Gk||c instanceof Ik||c instanceof Hk||c instanceof Jk)d=c;else if(ab(c)){d=[];for(var e=0;e<c.length;e++)d[e]=Lk(c[e],b)}else if("object"==typeof c){d=new Fk;for(var f in c)c.hasOwnProperty(f)&&d.set(b[f],Lk(c[f],b))}return d},Ok=function(a,b){for(var c=b?b.split(","):[],d=0;d<c.length;d++){var e=c[d]=c[d].split(":");0==a&&(e[1]=
Ak[e[1]]);if(1==a){var f=Nk(e[0]);e=c[d]={};for(var g=0;g<f.length;g++){var h=Bk[f[g]];e[h[0]]=h[1]}}if(2==a)for(g=0;4>g;g++)e[g]=Nk(e[g]);3==a&&(c[d]=Ak[e[0]]);if(4==a)for(g=0;2>g;g++)if(e[g]){e[g]=e[g].split(".");for(var k=0;k<e[g].length;k++)e[g][k]=Ak[e[g][k]]}else e[g]=[];5==a&&(c[d]=e[0])}return c},Nk=function(a){var b=[];if(!a)return b;for(var c=0,d=0;d<a.length&&c<zk;c+=6,d++){var e=a&&a.charCodeAt(d)||65;if(65!=e){var f;f=65<e&&90>=e?e-65:97<=e&&122>=e?e-97+26:95==e?63:48<=e?e-48+52:62;1&
f&&b.push(c);2&f&&b.push(c+1);4&f&&b.push(c+2);8&f&&b.push(c+3);16&f&&b.push(c+4);32&f&&b.push(c+5)}}return b},Pk=function(a,b,c){a.push.apply(a,Ok(b,c))};var Qk;
var Ug=function(a,b){if(null===a||void 0===a)return a;if(b.propertyRenamingRequired){var c={},d;for(d in a)if(a.hasOwnProperty(d)){var e=Tk[d];e&&0==e.indexOf("vtp_")&&(c[e]=a[d])}c.__metadata=b;return c}return a},Wk=function(a){},Xk=function(a,b){},Xg=function(a){};var Yk,Zk;var jl=function(a){return function(){}},kl=function(a){return function(){}};var ll=function(a){var b=this;this.i=a;this.ma=this.hc=!1;this.Ta=[];this.Na=[];this.w=function(){b.ma||Wf(b.Ta);Zf(b,1);if(Nb[a])for(var c=0;c<Nb[a].length;c++)Nb[a].shift().w()};this.C=function(){b.ma||Wf(b.Na);Zf(b,2);if(Nb[a])for(var c=0;c<Nb[a].length;c++)Nb[a].shift().C()};this.H=Lf},ml=function(a,b){a.Ta.push(b)},nl=function(a,b){a.Na.push(b)},ol=function(a){this.P=[];this.xb=[];this.Rb={};this.Xb=[];this.ca=0;this.ub={};this.zb={};this.yb={};this.event=a};ol.prototype.addListener=function(a){this.Xb.push(a)};
var pl=function(a){0<a.ca||Wf(a.Xb)},ql=function(a,b,c,d,e,f){if(!c.ma){a.P[b]=c;void 0==d&&(d=[]);void 0==e&&(e=[]);void 0==f&&(f=[]);d=ab(d)?d.slice():["or",d];e=ab(e)?e.slice():[e];f=ab(f)?f.slice():[f];a.Rb[b]=d;a.ub[b]=0<e.length;a.zb[b]=0<f.length;a.ca++;var g=function(){0<a.ca&&!a.ub[b]&&!a.zb[b]&&a.ca--;pl(a)};ml(c,g);nl(c,g)}},vl=function(a){for(var b=[],c={},d=0;d<a.P.length;c={X:c.X},d++)if(c.X=a.P[d],c.X){var e=a.Rb[d],f=a.ub[d],g=a.zb[d];if(0!=e.length||f||g){if(0<e.length)for(var h=
rl(e,c.X.H),k=0;k<e.length;k++)e[k]instanceof Jk&&e[k].D!=d&&sl(a,e[k].D,h);(f||g)&&tl(a,d,function(a){return function(){0<a.X.G.ca&&a.X.G.ca--;pl(a.X.G)}}(c))}else b.push(d)}for(d=0;d<b.length;d++)a.P[b[d]].H();for(d=0;d<a.xb.length;d++){var l=a.xb[d];ul(l);0<l.length&&l[0].H()}},sl=function(a,b,c){a.P[b]&&(ml(a.P[b],function(){c(b,!0)}),nl(a.P[b],function(){c(b,!1)}))},rl=function(a,b){var c=!1;return function(d,e){var f;a:{for(var g=0;g<a.length;g++)if(a[g]instanceof Jk&&a[g].D===d||a[g]===d){f=
g;break a}f=-1}c||0>f||("or"==a[0]?e?(c=!0,b()):(a.splice(f,1),1==a.length&&(c=!0)):e?(a.splice(f,1),1==a.length&&(c=!0,b())):c=!0)}},tl=function(a,b,c){var d=[],e=!1,f=function(b){var c,g,h=Ek[b];if(a.event.g(h)){}else g=wl(h,b,a.event.g,a);if(c=g){var k=xl(b,!0);0<k.length&&f(k[0].D);d.push(c);var l=xl(b,!1);0<l.length&&f(l[0].D)}else e=
!0};f(b);if(!e){for(var g=0;g<d.length;g++){var h=d[g],k=xl(h.i,!0);if(0<k.length){var l=d[g-1],m=yl(h);ml(l,m);0==k[0].ya?nl(l,m):nl(l,c)}var n=xl(h.i,!1);0<n.length&&(m=yl(d[g+1]),ml(h,m),0==n[0].ya?nl(h,m):nl(h,c))}ml(d[d.length-1],c);nl(d[d.length-1],c);a.xb.push(d)}},xl=function(a,b){var c=b?Oe:ef,d=Ek[a],e=void 0===d[c]?[]:d[c];return ab(e)?e:[e]},yl=function(a){return function(){a.H()}},ul=function(a){for(var b=[],c=0;c<a.length;c++){var d=a[c],e=d.i,f=Mb[e],g=f.firingOption;if(0!=g&&(1==g&&
void 0!==d.G.yb[e]||2==g&&void 0!==f.state)&&(b.push(d),2==f.state&&c!=a.length-1)){var h=xl(a[c+1].i,!0);if(0<h.length&&1==h[0].ya)for(++c;c<a.length;c++)b.push(a[c])}}var k=zl(b),l;for(l in k)if(k.hasOwnProperty(l)){for(var m=void 0,n=void 0,p=k[l],r=p[0],t=p[p.length-1],v,z=0;z<a.length;z++){var J=a[z];!m&&J.i==r&&0<z&&(m=a[z-1]);J.i==t&&z<a.length-1&&(n=a[z+1]);if(-1<Of(p,J.i))if(v=a.splice(z,1)[0],J.i==t)break;else z--}if(v){var F=Number(l),E=m,L=n;if(E){var B=E.Ta[0],D=E.Na[0],A=E;A.Ta=[];A.Na=
[];ml(E,B);nl(E,D)}if(E&&L){var C=yl(L);ml(E,C);var H=xl(E.i,!1);0<H.length&&H[0].D!=F&&0==H[0].ya&&nl(E,C);var I=xl(L.i,!0);0<I.length&&I[0].D!=F&&0==I[0].ya&&nl(E,C)}}}},zl=function(a){for(var b={},c=0;c<a.length;c++){var d=a[c],e=[],f=function(a){var b=xl(a,!0);0<b.length&&f(b[0].D);e.push(a);var c=xl(a,!1);0<c.length&&f(c[0].D)};f(d.i);b[d.i]=e}Al(a,b);return b},Al=function(a,b){for(var c=0;c<a.length;c++){var d=a[c].i,e;for(e in b)if(b.hasOwnProperty(e)&&e!=d&&-1<Of(b[e],d)){delete b[d];break}}};var Bl=function(a,b,c){return function(){a[Ad]=b.w;a[Bd]=b.C;var d=b.i,e=b.G&&b.G.yb[d],f=Mb[d]&&Mb[d].state,g=e?void 0!==e:b.hc||b.ma,h=Mb[d]&&Mb[d].firingOption,k=h&&2==h,l=h&&1==h;if(!g&&void 0===f||!g&&!k||!k&&!l){Zf(b,0);var m=b.G?b.G.event:void 0,n=a;n=Vg(n,new Rf,c);a=n;if(m){}Sf(a,b.w,b.C)}else k&&0==f||l&&0==e?Nb[d].push(b):k&&1==f||l&&1==e?b.w():b.C()}},wl=function(a,b,c,d){function e(a){return a.i===b}var f=function(){var a=d&&d.P;return a&&Pf(a,e)}()||new ll(b);f.G=d;ml(f,jl(a));nl(f,kl(a));f.H=Bl(a,f,c);return f};var Il=function(){var a=[];return function(b,c){if(void 0===a[b]){var d=Dk[b]&&Vg(Dk[b],new Rf,c),e=d;d&&(e=yk(d));a[b]=[e,d]}return a[b]}},Jl=function(a,b){for(var c=b[0],d=0;d<c.length;d++)if(!a.ba(c[d],a.g)[0])return!1;var e=b[2];for(d=0;d<e.length;d++)if(a.ba(e[d],a.g)[0])return!1;return!0},Kl=!1;
Lg=function(a,b,c,d,e){switch(b){case "gtm.js":if(Kl)return!1;Kl=!0;break;case "gtm.sync":if(Z("gtm.snippet")!=Jb)return!1}for(var f={id:a,name:b,Ga:d||Lf,ka:Nk(),Ra:Nk(),ba:Il(),g:Rg(c)},g=[],h=0;h<qh.length;h++)if(Jl(f,qh[h])){g[h]=!0;for(var k=f,l=qh[h],m=l[1],n=0;n<m.length;n++)k.ka[m[n]]=!0;var p=l[3];for(n=0;n<p.length;n++)k.Ra[p[n]]=!0}else g[h]=!1;var Q=[];for(var M=0;M<zk;M++)if(f.ka[M]&&!f.Ra[M])if(f.g(Ek[M])){}else{Q[M]=
Ek[M];}f.va=Q;for(var ma=new ol(f),da=0;da<zk;da++)if(f.ka[da]&&!f.Ra[da])if(f.g(Ek[da])){}else{var Ma=f.va[da],Lj=wl(Ma,da,f.g,ma);ql(ma,da,Lj,Ma[Yc],Ma[Oe],Ma[ef]);if(Ma[Ob])break}ma.addListener(f.Ga);vl(ma);pl(ma);e&&R(e)&&e({passingRules:g,resolvedTags:f.va});
if("gtm.js"==b||"gtm.sync"==b)a:{}for(var bg in f.va)if(f.va.hasOwnProperty(bg)){var cg=f.va[bg];if(void 0==cg[$a]||!$f(cg[$a],"_implicit"))return!0}return!1};var Ml=function(){};var Nl={};var Sl=function(){};var Ll={macro:function(a){if(Ck.contains(a))return Ck.get(a)}};Ll.dataLayer=zg;Ll.onHtmlSuccess=Yh(!0);Ll.onHtmlFailure=Yh(!1);Ll.callback=function(a){kb.hasOwnProperty(a)&&R(kb[a])&&kb[a]();delete kb[a]};
Ll.Dc=function(){var a=y.google_tag_manager;a||(a=y.google_tag_manager={});sb=a;if(a[Ha.f]){var b=sb.zones;b&&b.unregisterChild(Ha.f)}else{a[Ha.f]=Ll;ji();uh();Ak.push.apply(Ak,Mk());Pk(Bk,0,"2:0,2:1,3:2,6:3,0:4,1:5,2:7,4:8,28:8,31:9,33:10,18:11,19:11,16:8,5:12,33:13,5:14,2:15,3:16,25:17,11:12,0:18,1:19,1:20,26:11,28:11,21:22,31:23,2:24,3:25,9:26,14:11,30:11,36:11,37:11,12:11,17:11,15:11,23:27,20:28,32:8,5:29,2:30,3:31,25:32,0:33,1:34,21:36,5:37,1:38,21:40,22:41,5:42,2:43,3:44,0:45,1:46,21:47,5:49,1:50,2:51,3:52,25:53,11:54,29:8,13:55,0:56,1:57,2:59,27:60,5:61,21:62,5:64,1:65,21:66,22:66,5:68,3:69,0:70,1:71,3:72,0:73,1:74,21:76,20:77,5:78,2:79,8:80,10:81,2:82,3:83,35:84,5:85,2:87,5:88,5:90,5:92,5:94,2:96,39:97,40:98,38:8,24:11,34:58,5:99,5:101,5:103,5:105,3:106,7:107,3:108,7:109,3:110,7:111,2:112,3:113,3:114,3:115,25:116,3:117,25:118,3:119,25:120,3:121,3:122,3:123,3:124,3:125,25:126,3:127,25:128,3:129,25:130");Pk(Sg,1,"O,IAgH,IwBAw_D,IAgEAAAG,AAAAAAAAgB,IAgAAAAAAA-,IAgGAAAAAAAAg,IAgEAAAEAAAAAE,IAAAAAAAAAAAAAgB,IAAAAAAAAAAAAAgAAAD,IAAAAAAAAAAAAAgAAAM,IAAAAAAAAAAAAAgAAAw,IAAAAAAAAAAAAAAAAACD,KAAAAAAAAAAAAAAAAAAE,IAgEAAAAAAAAAAAAAAAY,IAgEAAAAAAAAAAAAAAAgB,IAgEAAAAAAAAAAAAAAAAG,IAgEAAAAAAAAAAAAAAAQI,IAgEAAAAAAAAAAAAAAAAR,IAgEAAAAAAAAAAAAAAAAk,AAAAAAAAgAAAAAAAAAAAAB,IAgEAAAAAAAAAAAAAAAAAG,IAgEAAAAAAAAAAAAAAAAAY,IAgEAAAAAAAAAAAAAAAAAgB");Pk(Dk,1,"x,BAAY,RAAg,AAAAAAAZ,BAAIAAAAC,AAAAAAABAG,RAAAAAAAAg,AAAAAAAAAABD,AAAAAAAJAAAAC,AAAAAAABAAAAAD,AAAAAAABAAAAAY");Pk(Ek,1,"I_H,Ivb,IjDAPA8,IjDALAcgB,IjDALAcAc,IjDALAcAAY,IAAAAAAAAAAc,IjDALAcAAAAgB,IjDALAcAAAAAc,I3DAJAQAAAAAAgD,ICAAAAAAAAAAAAcG,IAAAAAAAAAAAAAAY,IAAAAAAAAAAAAAAo,IAAAAAAAAAAAAAAIB,IAAAAAAAAAAAAAAIC,IAAAAAAAAAAAAAAA8H,IAAAAAAAAAAAAAAIAI,IAAAAAAAAAAAAAAIAQ,IAAAAAAAAAAAAAAIAg");Pk(qh,2,"B:Dw_B::,G:E::,M:I::,U:Q::,k:g::,AD:AB::,E:AC::,EE:AE::,EY:AI::");Pk(rh,4,"6.6.6.86.89.91.93.95.100.102.104:,21:,35:,39:,48:,58:,63:,67:,75:");for(var c=0;c<Ek.length;c++){var d=Ek[c],e=1;d[le]?e=2:
d[xf]&&(e=0);Mb[c]={firingOption:e,state:void 0};Nb[c]=[]}Ig();$g();var n=y;if("interactive"==K.readyState&&!K.createEventObject||"complete"==K.readyState)kg();else{va(K,"DOMContentLoaded",kg);va(K,"readystatechange",kg);if(K.createEventObject&&K.documentElement.doScroll){var p=!0;try{p=!n.frameElement}catch(J){}p&&mg()}va(n,"load",kg)}"complete"===K.readyState?rg():va(y,"load",rg);Sl();Ml();a:{}}};
Ll.Dc();var _vs="res_ts:1516866957213000,srv_cl:187209692,ds:live,cv:8";
})()
